### PR TITLE
First deliverable

### PR DESCRIPTION
**Pull request by michaloo**
https://trello.com/c/raY0Al4f/41-hubspot-ship

### CODE REVIEW

**Comment by unity** [comment]
Had to transform mapping-data.json to js because `import` doesn't import JSON files. was crashing in production

**Comment by unity** [comment]
Had to add assets folder serving to web-app.

I'd prefer if we sticked to the general file structure we've outlined for the slack bot for instance.
Is there a reason we packaged all of this into web.js, web-app.js and so on?

**Comment by unity** [comment]
@michaloo Install and Usage instructions need to be updated in the README

**Comment by unity** [comment]
I was trying to get /picture.png to work, it should be served from /assets/ but this folder isn't resolved by express anymore

**Comment by michaloo** [comment]
I've checked the JSON import file problem, this was because babel doesn't copy non JS files by default, adding `--copy-files` in the build script fixed that problem. But switching to JS file enables the mapping to have callbacks which could be an additional feature.

**Pull request merged**
